apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: simple-app
    name: simple-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: simple-app
    template:
      metadata:
        labels:
          app: simple-app
        name: simple-app
      spec:
        containers:
        - image: bendikp/python-simple:v0.0.1
          imagePullPolicy: IfNotPresent
          name: simple-app
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scheme: http
      prometheus.io/scrape: "true"
    labels:
      name: simple-app
    name: simple-app
  spec:
    ports:
    - name: simple-app
      port: 80
      protocol: TCP
      targetPort: 8000
    selector:
      app: simple-app
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: simple-app
  spec:
    to:
      name: simple-app
