apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: grafana
    name: grafana
  spec:
    replicas: 1
    selector:
      app: grafana
    template:
      metadata:
        labels:
          app: grafana
        name: grafana
      spec:
        containers:
        - image: grafana/grafana:4.6.1
          name: grafana
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: data-volume
        securityContext:
          runAsUser: 0
        serviceAccountName: grafana
        volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: grafana

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scheme: http
      prometheus.io/scrape: "true"
    labels:
      name: grafana
    name: grafana
  spec:
    ports:
    - name: grafana
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: grafana
  spec:
    to:
      name: grafana

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: grafana
